version: '3.8'

services:
  redis:
    image: redis:7.0.8-alpine3.17
    container_name: trends-cache
    volumes:
      - redis-data:/data
    networks:
      - trends-net

  postgres:
    image: postgres:15.2-alpine3.17
    container_name: trends-db
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password
      - POSTGRES_DB=trends
    networks:
      - trends-net

  backend:
    container_name: trends-backend
    image: trends-backend:1.0.2
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_NAME=trends
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
      - redis
    networks:
      - trends-net

volumes:
  postgres-data:
  redis-data:

networks:
  trends-net:
    driver: bridge